import body_up1 from "../../Img/body_up1.jpg";
import body_up2 from "../../Img/body_up2.jpg";
import body_up3 from "../../Img/body_up3.jpg";
import body_up4 from "../../Img/body_up4.jpg";
import body_up5 from "../../Img/body_up5.jpg";
import haoke1 from "../../Img/haoke1.png";
import haoke9 from "../../Img/haoke9.png";
import rumen7 from "../../Img/rumen7.jpeg";
import jineng6 from "../../Img/jineng6.png";
import jineng8 from "../../Img/jineng8.png";
import jishu10 from "../../Img/jishu10.jpeg";
// 好课图片
const haokePic = ['haoke2' , 'haoke3', 'haoke4', 'haoke5', 'haoke6', 'haoke7', 'haoke8', 'haoke10'];
const haoke = haokePic.map(item => require("../../Img/" + item + ".jpg"));
// 新手图片
const rumenPic = ['xinshou1','xinshou2','rumen1' , 'rumen2', 'rumen3', 'rumen4', 'rumen5', 'rumen6', 'rumen8', 'rumen9', 'rumen10'];
const rumen = rumenPic.map(item => require("../../Img/" + item + ".jpg"));
// 技能提升图片
const jinengPic = ['jineng-up1','jineng-up2','jineng1' , 'jineng2', 'jineng3','jineng4','jineng5' , 'jineng7' ,'jineng9' , 'jineng10', ];
const jineng = jinengPic.map(item => require("../../Img/" + item + ".jpg"));
// 前沿技术图片
const jishuPic = ['jishu-up1','jishu-up2','jishu1','jishu2','jishu3','jishu4','jishu5','jishu6','jishu7','jishu8','jishu9', ];
const jishu = jishuPic.map(item => require("../../Img/" + item + ".jpg"));
// 1新课 2升级

const data = [{
    bf:"fff",
    cardData:"",
    title:["实","／","战","／","推","／","荐"],
    titIconL:"title-icon icon-shizhan-l tit-icon-l",
    titIconR:"title-icon icon-shizhan-r tit-icon-r",
    cardData1 : [{
        id:0,
        img:body_up1,
        sLogo:'',
        span:[''],
        h3:'大前端—前端全能进阶',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥1999.00',
        cost:'￥2680.00',
        star:'5',
        stime:'',
    },{
        id:0,
        img:body_up2,
        sLogo:'',
        span:['Python'],
        h3:'全面系统python3入门+进阶课程 小白也能听懂',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥366.00',
        cost:'',
        star:'5',
        stime:'',
    },{
        id:2,
        img:body_up3,
        sLogo:'升级',
        span:['微服务','Spring Cloud'],
        h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
        class:'实战',
        course:'高级',
        count:'4354',
        price:'￥366.00',
        cost:'',
        star:'5',
        stime:'',
    },{
        id:0,
        img:body_up4,
        sLogo:'',
        span:['Java','算法与数据结构'],
        h3:'剑指Java面试-Offer直通车',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥299.00',
        cost:'',
        star:'5',
        stime:'',
    },{
        id:0,
        img:body_up5,
        sLogo:'',
        span:['计算机网络'],
        h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
        class:'实战',
        course:'中级',
        count:'1528',
        price:'￥239.00',
        cost:'',
        star:'5',
        stime:'',
    },],
},{
    bf:"",
    cardData:"",
    title:["新","／","上","／","好","／","课"],
    titIconL:"title-icon icon-haoke-l tit-icon-l",
    titIconR:"title-icon icon-haoke-r tit-icon-r",
    cardData1 : [{
        id:1,
        img:haoke1,
        sLogo:'新课',
        span:['Java'],
        h3:' 告别996，开启Java高效编程之门',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥249.00',
        cost:'￥288.00',
        star:'5',
        stime:'限时优惠',
    },{
        id:1,
        img:haoke[2],
        sLogo:'新课',
        span:['SpringBoot','SpringCloud'],
        h3:'Spring Cloud微服务安全实战',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥255.00',
        cost:'￥299.00',
        star:'5',
        stime:'限时优惠',
    },{
        id:1,
        img:haoke[3],
        sLogo:'新课',
        span:['算法','算法与数据结构'],
        h3:'玩转算法系列--图论精讲  面试升职必备（Java版）',
        class:'实战',
        course:'高级',
        count:'424',
        price:'￥348.00',
        cost:'',
        star:'5',
        stime:'限时优惠',
    },{
        id:1,
        img:haoke[4],
        sLogo:'新课',
        span:['Linux'],
        h3:'Linux核心技能与应用',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥225.00',
        cost:'￥299.00',
        star:'5',
        stime:'限时优惠',
    },{
        id:1,
        img:haoke[5],
        sLogo:'新课',
        span:['Android'],
        h3:'企业级Android应用架构设计与开发',
        class:'实战',
        course:'中级',
        count:'128',
        price:'￥255.00',
        cost:'￥299.00',
        star:'5',
        stime:'限时优惠',
    }],
    cardData2 : [{
        id:1,
        img:haoke[6],
        sLogo:'新课',
        span:['React.JS','Sass/Less'],
        h3:'Electron+React+七牛云 实战跨平台桌面应用',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥249.00',
        cost:'￥288.00',
        star:'5',
        stime:'限时优惠',
    },{
        id:0,
        img:haoke[7],
        sLogo:'',
        span:['接口测试'],
        h3:'Python接口自动化测试框架实战 从设计到开发',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥299.00',
        cost:'',
        star:'5',
        stime:'',
    },{
        id:1,
        img:haoke9,
        sLogo:'新课',
        span:['算法','算法与数据结构'],
        h3:'玩转算法系列--图论精讲  面试升职必备（Java版）',
        class:'实战',
        course:'高级',
        count:'424',
        price:'免费',
        cost:'',
        star:'0',
        stime:'',
    },{
        id:0,
        img:haoke[1],
        sLogo:'',
        span:['微服务','Spring Cloud'],
        h3:'Spring Cloud微服务实战 打造企业级优惠券系统',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥255.00',
        cost:'',
        star:'5',
        stime:'',
    },{
        id:1,
        img:haoke[0],
        sLogo:'新课',
        span:['Java'],
        h3:'一站式学习Java网络编程 全面理解BIO/NIO/AIO',
        class:'实战',
        course:'中级',
        count:'128',
        price:'￥255.00',
        cost:'￥299.00',
        star:'0',
        stime:'优惠价',
    },],
},{
    bf:"fff",
    title:["新","／","手","／","入","／","门"],
    titIconL:"title-icon icon-rumen-l tit-icon-l",
    titIconR:"title-icon icon-rumen-r tit-icon-r",
    cardData : [{
        img:rumen[0],
        h3:'站上微信小程序风口，实现职业华丽转身',
        p:'入门技能+项目开发，逐步深入学习微信小程序开发',
    },{
        img:rumen[1],
        h3:'盘点最主流的前端框架有哪些？',
        p:'上万人的选择打消你对主流框架的疑惑',
    },],
    cardData1 : [{
    id:1,
    img:rumen[8],
    sLogo:'新课',
    span:[''],
    h3:'大前端—前端全能进阶',
    class:'就业班',
    course:'实战',
    count:'98',
    price:'￥1999.00',
    cost:'￥2680.00',
    star:'5',
},{
    id:0,
    img:rumen[9],
    sLogo:'',
    span:['Python'],
    h3:'全面系统python3入门+进阶课程 小白也能听懂',
    class:'实战',
    course:'初级',
    count:'9342',
    price:'￥366.00',
    cost:'',
    star:'5',
},{
    id:2,
    img:rumen[2],
    sLogo:'升级',
    span:['微服务','Spring Cloud'],
    h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
    class:'实战',
    course:'高级',
    count:'4354',
    price:'￥366.00',
    cost:'',
    star:'5',
},{
    id:0,
    img:rumen[3],
    sLogo:'',
    span:['Java','算法与数据结构'],
    h3:'剑指Java面试-Offer直通车',
    class:'实战',
    course:'中级',
    count:'98',
    price:'￥299.00',
    cost:'',
    star:'5',
},{
    id:0,
    img:rumen[4],
    sLogo:'',
    span:['计算机网络'],
    h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
    class:'实战',
    course:'中级',
    count:'1528',
    price:'￥239.00',
    cost:'',
    star:'5',
},],
    cardData2 : [{
    id:1,
    img:rumen[5],
    sLogo:'新课',
    span:[''],
    h3:'大前端—前端全能进阶',
    class:'就业班',
    course:'实战',
    count:'98',
    price:'￥1999.00',
    cost:'￥2680.00',
    star:'5',
},{
    id:0,
    img:rumen[6],
    sLogo:'',
    span:['Python'],
    h3:'全面系统python3入门+进阶课程 小白也能听懂',
    class:'实战',
    course:'初级',
    count:'9342',
    price:'￥366.00',
    cost:'',
    star:'5',
},{
    id:2,
    img:rumen7,
    sLogo:'升级',
    span:['微服务','Spring Cloud'],
    h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
    class:'实战',
    course:'高级',
    count:'4354',
    price:'￥366.00',
    cost:'',
    star:'5',
},{
    id:0,
    img:rumen[8],
    sLogo:'',
    span:['Java','算法与数据结构'],
    h3:'剑指Java面试-Offer直通车',
    class:'实战',
    course:'中级',
    count:'98',
    price:'￥299.00',
    cost:'',
    star:'5',
},{
    id:0,
    img:rumen[7],
    sLogo:'',
    span:['计算机网络'],
    h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
    class:'实战',
    course:'中级',
    count:'1528',
    price:'￥239.00',
    cost:'',
    star:'5',
},],
}, {
    bf:"",
    title:["技","／","能","／","提","／","升"],
    titIconL:"title-icon icon-jineng-l tit-icon-l",
    titIconR:"title-icon icon-jineng-r tit-icon-r",
    cardData : [{
        img:jineng[0],
        h3:'Vue高级工程师实战之路',
        p:'从Vue基础语法入门最流行的SSR技术实现，完美学习路线打造快速晋升之路！',
    },{
        img:jineng[1],
        h3:'Python开发一站式学习',
        p:'从入门到开发，学习 好玩 好用 好未来的Python语言',
    },],
    cardData1 : [{
        id:1,
        img:jineng[8],
        sLogo:'新课',
        span:[''],
        h3:'大前端—前端全能进阶',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥1999.00',
        cost:'￥2680.00',
        star:'5',
    },{
        id:0,
        img:jineng[9],
        sLogo:'',
        span:['Python'],
        h3:'全面系统python3入门+进阶课程 小白也能听懂',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:2,
        img:jineng[2],
        sLogo:'升级',
        span:['微服务','Spring Cloud'],
        h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
        class:'实战',
        course:'高级',
        count:'4354',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jineng[3],
        sLogo:'',
        span:['Java','算法与数据结构'],
        h3:'剑指Java面试-Offer直通车',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥299.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jineng[4],
        sLogo:'',
        span:['计算机网络'],
        h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
        class:'实战',
        course:'中级',
        count:'1528',
        price:'￥239.00',
        cost:'',
        star:'5',
    },],
    cardData2 : [{
        id:1,
        img:jineng[5],
        sLogo:'新课',
        span:[''],
        h3:'大前端—前端全能进阶',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥1999.00',
        cost:'￥2680.00',
        star:'5',
    },{
        id:0,
        img:jineng[6],
        sLogo:'',
        span:['Python'],
        h3:'全面系统python3入门+进阶课程 小白也能听懂',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:2,
        img:jineng6,
        sLogo:'升级',
        span:['微服务','Spring Cloud'],
        h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
        class:'实战',
        course:'高级',
        count:'4354',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jineng[8],
        sLogo:'',
        span:['Java','算法与数据结构'],
        h3:'剑指Java面试-Offer直通车',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥299.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jineng8,
        sLogo:'',
        span:['计算机网络'],
        h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
        class:'实战',
        course:'中级',
        count:'1528',
        price:'￥239.00',
        cost:'',
        star:'5',
    },],
}, {
    bf:"fff",
    title:["前","／","沿","／","技","／","术"],
    titIconL:"title-icon icon-jishu-l tit-icon-l",
    titIconR:"title-icon icon-jishu-r tit-icon-r",
    cardData : [{
        img:jishu[0],
        h3:'慕课微课',
        p:'超值课程最低一元体验',
    },{
        img:jishu[1],
        h3:'改变职场命运，修炼全栈工程师的必修课',
        p:'练就编程十八般武艺，快速转型全栈开发，做全能型工程师！',
    },],
    cardData1 : [{
        id:1,
        img:jishu[8],
        sLogo:'新课',
        span:[''],
        h3:'大前端—前端全能进阶',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥1999.00',
        cost:'￥2680.00',
        star:'5',
    },{
        id:0,
        img:jishu[9],
        sLogo:'',
        span:['Python'],
        h3:'全面系统python3入门+进阶课程 小白也能听懂',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:2,
        img:jishu[2],
        sLogo:'升级',
        span:['微服务','Spring Cloud'],
        h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
        class:'实战',
        course:'高级',
        count:'4354',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jishu[3],
        sLogo:'',
        span:['Java','算法与数据结构'],
        h3:'剑指Java面试-Offer直通车',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥299.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jishu[4],
        sLogo:'',
        span:['计算机网络'],
        h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
        class:'实战',
        course:'中级',
        count:'1528',
        price:'￥239.00',
        cost:'',
        star:'5',
    },],
    cardData2 : [{
        id:1,
        img:jishu[5],
        sLogo:'新课',
        span:[''],
        h3:'大前端—前端全能进阶',
        class:'就业班',
        course:'实战',
        count:'98',
        price:'￥1999.00',
        cost:'￥2680.00',
        star:'5',
    },{
        id:0,
        img:jishu[6],
        sLogo:'',
        span:['Python'],
        h3:'全面系统python3入门+进阶课程 小白也能听懂',
        class:'实战',
        course:'初级',
        count:'9342',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:2,
        img:jishu10,
        sLogo:'升级',
        span:['微服务','Spring Cloud'],
        h3:'SpringCloud  Finchley三版本(M2+RELEASE+SR2)微服务实战',
        class:'实战',
        course:'高级',
        count:'4354',
        price:'￥366.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jishu[8],
        sLogo:'',
        span:['Java','算法与数据结构'],
        h3:'剑指Java面试-Offer直通车',
        class:'实战',
        course:'中级',
        count:'98',
        price:'￥299.00',
        cost:'',
        star:'5',
    },{
        id:0,
        img:jishu[7],
        sLogo:'',
        span:['计算机网络'],
        h3:'编程必备基础知识 计算机组成原理+操作系统+计算机网络',
        class:'实战',
        course:'中级',
        count:'1528',
        price:'￥239.00',
        cost:'',
        star:'5',
    },],
},];


export {data};